/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pims.gui;

import pims.BackgroundPanel;

/**
 *
 * @author natan
 */
public class LoginForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        setContentPane(new BackgroundPanel());
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JUsername1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JLabel();
        txtUsername = new pims.RoundedTextfield();
        btnLogin = new pims.RoundedButton("Login", new java.awt.Color(51, 102, 0), java.awt.Color.WHITE);
        toggleBtn = new javax.swing.JButton();
        txtPassword = new pims.RoundedPassword();
        jPanel2 =    new pims.CardPanel(20);
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HealthFirst Pharmacy - Login");
        setBackground(new java.awt.Color(245, 249, 247));
        setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JUsername1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        JUsername1.setForeground(new java.awt.Color(51, 51, 51));
        JUsername1.setText("Username");
        getContentPane().add(JUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 230, 20));

        jPasswordField1.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setText("Password");
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 61, -1));

        txtUsername.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtUsername.setText("");
        txtUsername.setBorder(null);
        txtUsername.setSelectionEnd(15);
        txtUsername.setSelectionStart(15);
        txtUsername.addActionListener(this::txtUsernameActionPerformed);
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 230, 30));

        btnLogin.setBackground(new java.awt.Color(51, 102, 0));
        btnLogin.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 110, 40));

        toggleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pims/images/eye_open.png"))); // NOI18N
        toggleBtn.setBorderPainted(false);
        toggleBtn.setContentAreaFilled(false);
        toggleBtn.setFocusPainted(false);
        toggleBtn.setPreferredSize(new java.awt.Dimension(523, 22));
        toggleBtn.setSelected(true);
        toggleBtn.addActionListener(this::toggleBtnActionPerformed1);
        getContentPane().add(toggleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 20, 30));

        txtPassword.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.addActionListener(this::txtPasswordActionPerformed);
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 230, 30));

        lblError.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 280, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            lblError.setText("Please enter username and password");
            return;
        }

        try {
            pims.dao.UserDAO userDAO = new pims.dao.UserDAO();
            pims.model.User user = userDAO.validateLogin(username, password);

            if (user == null) {
                lblError.setText("Invalid username or password");
                return;
            }

            // Login successful - redirect based on role
            this.dispose(); // close the login window

            if (user.getRole().equals("Admin")) {
    new pims.gui.AdminDashboard().setVisible(true);
} else {
    new pims.gui.CashierDashboard(user).setVisible(true);
}

        } catch (java.sql.SQLException e) {
            lblError.setText("Database error - check connection");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLoginActionPerformed
    private boolean passwordVisible = false;
    private void toggleBtnActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleBtnActionPerformed1
        passwordVisible = !passwordVisible;

        String path = passwordVisible
                ? "/pims/images/eye_closed.png"
                : "/pims/images/eye_open.png";

        java.net.URL url = getClass().getResource(path);

        if (url != null) {
            toggleBtn.setIcon(new javax.swing.ImageIcon(url));
        }

        txtPassword.setEchoChar(passwordVisible ? (char) 0 : '*');


    }//GEN-LAST:event_toggleBtnActionPerformed1

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JUsername1;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jPasswordField1;
    private javax.swing.JLabel lblError;
    private javax.swing.JButton toggleBtn;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
