/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pims.gui;

import pims.BackgroundPanel;
import pims.dao.MedicineDAO;
import pims.model.Medicine;

/**
 *
 * @author natan
 */
public class ManageMedicinesForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageMedicinesForm.class.getName());
    private javax.swing.table.DefaultTableModel tableModel;

    /**
     * Creates new form ManageMedicines
     */
    public ManageMedicinesForm() {
        setContentPane(new BackgroundPanel());
        initComponents();
        loadMedicinesTable();
    }

    private void loadMedicinesTable() {
        String[] columns = {"ID", "Name", "Company", "Type", "Price", "Qty"};
        tableModel = new javax.swing.table.DefaultTableModel(columns, 0);
        tblMedicines.setModel(tableModel);

        try {
            MedicineDAO dao = new MedicineDAO();
            java.util.List<Medicine> medicines = dao.getAllMedicines();

            for (Medicine m : medicines) {
                tableModel.addRow(new Object[]{
                    m.getMedicineId(),
                    m.getName(),
                    m.getCompany(),
                    m.getMedicineType(),
                    m.getPrice(),
                    m.getQuantityInStock()
                });
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading medicines: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void clearForm() {
        txtName.setText("");
        txtCompany.setText("");
        txtType.setText("");
        txtPrice.setText("");
        txtQuantity.setText("");
        txtReorderLevel.setText("");
        txtExpiryDate.setText("");
        txtSupplierId.setText("");
        tblMedicines.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicines = new javax.swing.JTable();
        lblName = new javax.swing.JLabel();
        lblCompany = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblReorderLevel = new javax.swing.JLabel();
        lblExpiryDate = new javax.swing.JLabel();
        lblSupplierId = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCompany = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtReorderLevel = new javax.swing.JTextField();
        txtExpiryDate = new javax.swing.JTextField();
        txtSupplierId = new javax.swing.JTextField();
        btnAdd = new pims.RoundedButton("Add", new java.awt.Color(51, 102, 0), java.awt.Color.WHITE);
        btnUpdate = new pims.RoundedButton("Update", new java.awt.Color(51, 102, 0), java.awt.Color.WHITE);
        btnDelete = new pims.RoundedButton("Delete", new java.awt.Color(51, 102, 0), java.awt.Color.WHITE);
        btnClear = new pims.RoundedButton("Clear", new java.awt.Color(51, 102, 0), java.awt.Color.WHITE);
        jButton1 = new pims.RoundedButton("<", new java.awt.Color(51, 102, 0), java.awt.Color.WHITE);
        jLabel1 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblMedicines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMedicines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMedicinesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMedicines);

        lblName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblName.setText("Name");

        lblCompany.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCompany.setText("Company");

        lblPrice.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPrice.setText("Price");

        lblQuantity.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblQuantity.setText("Quantity");

        lblReorderLevel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblReorderLevel.setText("Reorder level");

        lblExpiryDate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblExpiryDate.setText("Expiry date");

        lblSupplierId.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSupplierId.setText("Supplier ID");

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton1.setText("<");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Type");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Medicine");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblSupplierId, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(lblReorderLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtName)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtReorderLevel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtSupplierId))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblExpiryDate, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(lblQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(lblCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(txtCompany)
                                        .addComponent(txtQuantity, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtExpiryDate)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtType))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblCompany))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(lblQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReorderLevel)
                    .addComponent(lblExpiryDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReorderLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierId)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupplierId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblMedicinesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMedicinesMouseClicked
        int row = tblMedicines.getSelectedRow();
        if (row == -1) {
            return;
        }

        txtName.setText(tableModel.getValueAt(row, 1).toString());
        txtCompany.setText(tableModel.getValueAt(row, 2).toString());
        txtType.setText(tableModel.getValueAt(row, 3).toString());
        txtPrice.setText(tableModel.getValueAt(row, 4).toString());
        txtQuantity.setText(tableModel.getValueAt(row, 5).toString());

        int medicineId = (int) tableModel.getValueAt(row, 0);
        try {
            MedicineDAO dao = new MedicineDAO();
            java.util.List<Medicine> all = dao.getAllMedicines();
            for (Medicine m : all) {
                if (m.getMedicineId() == medicineId) {
                    txtReorderLevel.setText(String.valueOf(m.getReorderLevel()));
                    txtExpiryDate.setText(m.getExpiryDate().toString());
                    txtSupplierId.setText(m.getSupplierId() != null ? m.getSupplierId().toString() : "");
                    break;
                }
            }
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblMedicinesMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String name = txtName.getText().trim();
            String company = txtCompany.getText().trim();
            String type = txtType.getText().trim();

            if (name.isEmpty() || txtPrice.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Name and Price are required.");
                return;
            }

            java.math.BigDecimal price = new java.math.BigDecimal(txtPrice.getText().trim());
            int quantity = Integer.parseInt(txtQuantity.getText().trim());
            int reorderLevel = txtReorderLevel.getText().trim().isEmpty() ? 10 : Integer.parseInt(txtReorderLevel.getText().trim());
            java.sql.Date expiryDate = java.sql.Date.valueOf(txtExpiryDate.getText().trim());

            Integer supplierId = txtSupplierId.getText().trim().isEmpty()
                    ? null
                    : Integer.parseInt(txtSupplierId.getText().trim());

            Medicine newMedicine = new Medicine(0, name, company, type, price, quantity, reorderLevel, expiryDate, supplierId);

            MedicineDAO dao = new MedicineDAO();
            dao.addMedicine(newMedicine);

            javax.swing.JOptionPane.showMessageDialog(this, "Medicine added successfully!");
            clearForm();
            loadMedicinesTable();

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Price, Quantity, Reorder Level, and Supplier ID must be numbers.");
        } catch (IllegalArgumentException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Expiry date must be in YYYY-MM-DD format.");
        } catch (java.sql.SQLException e) {
            if (e.getMessage().contains("foreign key constraint")) {
                javax.swing.JOptionPane.showMessageDialog(this, "That Supplier ID doesn't exist. Leave it blank or enter a valid supplier ID.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
            }
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = tblMedicines.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a medicine from the table first.");
            return;
        }

        try {
            int medicineId = (int) tableModel.getValueAt(row, 0);

            String name = txtName.getText().trim();
            String company = txtCompany.getText().trim();
            String type = txtType.getText().trim();
            java.math.BigDecimal price = new java.math.BigDecimal(txtPrice.getText().trim());
            int quantity = Integer.parseInt(txtQuantity.getText().trim());
            int reorderLevel = Integer.parseInt(txtReorderLevel.getText().trim());
            java.sql.Date expiryDate = java.sql.Date.valueOf(txtExpiryDate.getText().trim());
            Integer supplierId = txtSupplierId.getText().trim().isEmpty()
                    ? null
                    : Integer.parseInt(txtSupplierId.getText().trim());

            Medicine updated = new Medicine(medicineId, name, company, type, price, quantity, reorderLevel, expiryDate, supplierId);

            MedicineDAO dao = new MedicineDAO();
            dao.updateMedicine(updated);

            javax.swing.JOptionPane.showMessageDialog(this, "Medicine updated successfully!");
            clearForm();
            loadMedicinesTable();

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Price, Quantity, Reorder Level, and Supplier ID must be numbers.");
        } catch (IllegalArgumentException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Expiry date must be in YYYY-MM-DD format.");
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tblMedicines.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a medicine from the table first.");
            return;
        }

        int medicineId = (int) tableModel.getValueAt(row, 0);
        String name = tableModel.getValueAt(row, 1).toString();

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Delete \"" + name + "\"? This cannot be undone.",
                "Confirm Delete",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                MedicineDAO dao = new MedicineDAO();
                dao.deleteMedicine(medicineId);
                javax.swing.JOptionPane.showMessageDialog(this, "Medicine deleted.");
                clearForm();
                loadMedicinesTable();
            } catch (java.sql.SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblExpiryDate;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblReorderLevel;
    private javax.swing.JLabel lblSupplierId;
    private javax.swing.JTable tblMedicines;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtExpiryDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtReorderLevel;
    private javax.swing.JTextField txtSupplierId;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
