/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pims.gui;

import pims.BackgroundPanel;

/**
 *
 * @author natan
 */
public class POSForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(POSForm.class.getName());
    private java.util.List<pims.model.Medicine> searchResultsList = new java.util.ArrayList<>();
    private java.util.List<pims.model.CartItem> cart = new java.util.ArrayList<>();
    private pims.model.User currentUser;
    /**
     * Creates new form POSForm
     */
    public POSForm(pims.model.User user) {
        setContentPane(new BackgroundPanel());
        initComponents();
        this.currentUser = user;
         btnSearchActionPerformed(null);
    }

    private void refreshCartTable() {
        javax.swing.table.DefaultTableModel model
                = new javax.swing.table.DefaultTableModel(
                        new Object[]{"Name", "Qty", "Unit Price", "Subtotal"}, 0);

        java.math.BigDecimal total = java.math.BigDecimal.ZERO;

        for (pims.model.CartItem ci : cart) {
            model.addRow(new Object[]{
                ci.getMedicine().getName(),
                ci.getQuantity(),
                ci.getMedicine().getPrice(),
                ci.getSubtotal()
            });
            total = total.add(ci.getSubtotal());
        }

        tblCart.setModel(model);
        lblTotal.setText("Total: R" + total.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new pims.RoundedTextfield();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchResults = new javax.swing.JTable();
        txtQuantity = new javax.swing.JTextField();
        btnAddToCart = new pims.RoundedButton("Add To Cart", new java.awt.Color(51, 102, 0), java.awt.Color.WHITE);
        btnRemoveFromCart = new pims.RoundedButton("Remove", new java.awt.Color(51, 102, 0), java.awt.Color.WHITE);
        btnClearCart = new pims.RoundedButton("Clear", new java.awt.Color(51, 102, 0), java.awt.Color.WHITE);
        lblTotal = new javax.swing.JLabel();
        btnCheckout = new pims.RoundedButton("Checkout", new java.awt.Color(51, 102, 0), java.awt.Color.WHITE);
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new pims.RoundedButton("<", new java.awt.Color(51, 102, 0), java.awt.Color.WHITE);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtSearch.setToolTipText("");

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pims/images/search-button.png"))); // NOI18N
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        tblSearchResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Price", "In Stock"
            }
        ));
        jScrollPane1.setViewportView(tblSearchResults);

        txtQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantity.setText("1");

        btnAddToCart.setText("Add To Cart");
        btnAddToCart.addActionListener(this::btnAddToCartActionPerformed);

        btnRemoveFromCart.setText("Remove");
        btnRemoveFromCart.addActionListener(this::btnRemoveFromCartActionPerformed);

        btnClearCart.setText("Clear");
        btnClearCart.addActionListener(this::btnClearCartActionPerformed);

        lblTotal.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        lblTotal.setText("Total: R0.00");

        btnCheckout.setText("Checkout");
        btnCheckout.addActionListener(this::btnCheckoutActionPerformed);

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Qty", "Unit Price", "Subtotal"
            }
        ));
        jScrollPane2.setViewportView(tblCart);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel1.setText("Quantity");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("<");
        jButton1.setToolTipText("");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Inventory Selection");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("   Shopping Cart");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRemoveFromCart, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClearCart, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddToCart)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveFromCart)
                    .addComponent(btnClearCart))
                .addGap(18, 18, 18)
                .addComponent(lblTotal)
                .addGap(27, 27, 27)
                .addComponent(btnCheckout)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keyword = txtSearch.getText().trim().toLowerCase();

        try {
            pims.dao.MedicineDAO dao = new pims.dao.MedicineDAO();
            java.util.List<pims.model.Medicine> all = dao.getAllMedicines();

            searchResultsList.clear();
            for (pims.model.Medicine m : all) {
                if (keyword.isEmpty() || m.getName().toLowerCase().contains(keyword)) {
                    searchResultsList.add(m);
                }
            }

            javax.swing.table.DefaultTableModel model
                    = new javax.swing.table.DefaultTableModel(
                            new Object[]{"ID", "Name", "Price", "In Stock"}, 0);

            for (pims.model.Medicine m : searchResultsList) {
                model.addRow(new Object[]{
                    m.getMedicineId(), m.getName(), m.getPrice(), m.getQuantityInStock()
                });
            }
            tblSearchResults.setModel(model);

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        int row = tblSearchResults.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a medicine from the search results first.");
            return;
        }

        int qty;
        try {
            qty = Integer.parseInt(txtQuantity.getText().trim());
            if (qty <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Quantity must be greater than 0.");
                return;
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Enter a valid quantity.");
            return;
        }

        pims.model.Medicine selected = searchResultsList.get(row);

        // check how much of this medicine is already in the cart
        int alreadyInCart = 0;
        for (pims.model.CartItem ci : cart) {
            if (ci.getMedicine().getMedicineId() == selected.getMedicineId()) {
                alreadyInCart = ci.getQuantity();
                break;
            }
        }

        if (qty + alreadyInCart > selected.getQuantityInStock()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Not enough stock. Available: " + selected.getQuantityInStock() + ", already in cart: " + alreadyInCart);
            return;
        }

        // if already in cart, increase quantity instead of duplicating the row
        boolean found = false;
        for (pims.model.CartItem ci : cart) {
            if (ci.getMedicine().getMedicineId() == selected.getMedicineId()) {
                ci.setQuantity(ci.getQuantity() + qty);
                found = true;
                break;
            }
        }
        if (!found) {
            cart.add(new pims.model.CartItem(selected, qty));
        }

        refreshCartTable();
        txtQuantity.setText("1");
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void btnRemoveFromCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFromCartActionPerformed
        int row = tblCart.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select an item in the cart to remove.");
            return;
        }
        cart.remove(row);
        refreshCartTable();
    }//GEN-LAST:event_btnRemoveFromCartActionPerformed

    private void btnClearCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCartActionPerformed
        cart.clear();
        refreshCartTable();
    }//GEN-LAST:event_btnClearCartActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        if (cart.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Cart is empty.");
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Confirm checkout for " + lblTotal.getText() + "?",
            "Confirm Checkout", javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

    java.math.BigDecimal total = java.math.BigDecimal.ZERO;
    for (pims.model.CartItem ci : cart) {
        total = total.add(ci.getSubtotal());
    }

    try {
        pims.dao.SaleDAO saleDao = new pims.dao.SaleDAO();
        int saleId = saleDao.checkout(cart, currentUser.getUserId(), total);

        new pims.gui.BillForm(saleId, new java.util.ArrayList<>(cart), total, currentUser).setVisible(true);

        cart.clear();
        refreshCartTable();
        btnSearchActionPerformed(null); // refresh search results so updated stock shows

    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Checkout failed: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnClearCart;
    private javax.swing.JButton btnRemoveFromCart;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCart;
    private javax.swing.JTable tblSearchResults;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
